debugging: true

exclude: [bower_components, node_modules, glyphs]

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# location of stylesheets:
css: /css



